sudo: required
servcies:
  - docker
before_install:
  - docker build -t namrutha/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true namrutha/docker-react npm run test
language: generic

